Repository openhab/openhab1-addons, pull requests merged in 2018-12, with the labels that each got.

#5721 [Telegram] Add support for file protocol
  bundles/action/org.openhab.action.telegram/README.md
  bundles/action/org.openhab.action.telegram/src/main/java/org/openhab/action/telegram/internal/Telegram.java
Labels: enhancement

#5701 [VDR] Update README.md
  bundles/binding/org.openhab.binding.vdr/README.md
Labels: documentation

#5710 [TCP Binding] Enhancements for README.md
  bundles/binding/org.openhab.binding.tcp/README.md
Labels: awaiting-feedback, documentation

#5738 [JDBC/MySQL Persistence] Updated connector to version 8.0
  pom.xml
Labels: enhancement
