Repository openhab/openhab1-addons, pull requests merged in 2018-09, with the labels that each got.

#5653 Update README.md
  bundles/binding/org.openhab.binding.mqtt/README.md
Labels: documentation

#5646 [Ecobee] Update README.md
  bundles/binding/org.openhab.binding.ecobee/README.md
Labels: documentation

#5656 [fritzboxtr064] replaced the trim method, to get rid of white spaces in between the tel numbers
  bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/PhonebookManager.java
Labels: enhancement

#5660 [Pushover] Updates to reflect language used in the API
  bundles/action/org.openhab.action.pushover/README.md
Labels: documentation

#5652 removed irrelevant implementations of autoUpdate feature as a cleanup…
  bundles/binding/org.openhab.binding.alarmdecoder/src/main/java/org/openhab/binding/alarmdecoder/AlarmDecoderBindingProvider.java
  bundles/binding/org.openhab.binding.alarmdecoder/src/main/java/org/openhab/binding/alarmdecoder/internal/AlarmDecoderGenericBindingProvider.java
  bundles/binding/org.openhab.binding.hdanywhere/src/main/java/org/openhab/binding/hdanywhere/HDanywhereBindingProvider.java
  bundles/binding/org.openhab.binding.hdanywhere/src/main/java/org/openhab/binding/hdanywhere/internal/HDanywhereGenericBindingProvider.java
  bundles/binding/org.openhab.binding.ihc/OSGI-INF/genericbindingprovider.xml
  bundles/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/IhcGenericBindingProvider.java
  bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/InsteonPLMBindingProvider.java
  bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/InsteonPLMGenericBindingProvider.java
  bundles/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/PlugwiseBindingProvider.java
  bundles/binding/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/PlugwiseGenericBindingProvider.java
  bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/ZWaveBindingProvider.java
  bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/ZWaveGenericBindingProvider.java
Labels: build-or-ide

#5345 [Twitter] New function allowing to tweet with an attached picture.
  bundles/action/org.openhab.action.twitter/README.md
  bundles/action/org.openhab.action.twitter/src/main/java/org/openhab/action/twitter/internal/Twitter.java
Labels: awaiting-feedback, enhancement, stale

#5671 [Persistence][Documentation] Small change to highlight the mandatory use of the everyMinute strategy
  bundles/persistence/org.openhab.persistence.rrd4j/README.md
Labels: documentation
