Repository openhab/openhab1-addons, pull requests merged in 2018-11, with the labels that each got.

#5688 [Pilight] update URL for Pilight wiring link
  bundles/binding/org.openhab.binding.pilight/README.md
Labels: documentation

#5699 [persistence/mysql] Update mysql connector
  bundles/persistence/org.openhab.persistence.mysql/META-INF/MANIFEST.MF
  bundles/persistence/org.openhab.persistence.mysql/build.properties
  bundles/persistence/org.openhab.persistence.mysql/lib/mysql-connector-java-5.1.26-bin.jar
  bundles/persistence/org.openhab.persistence.mysql/lib/mysql-connector-java-8.0.13.jar
Labels: enhancement

#5707 [PLCBus] Fix addon crash when two commands are sent in quick succession
  bundles/binding/org.openhab.binding.plcbus/src/main/java/org/openhab/binding/plcbus/internal/protocol/AbstractReceiveFrameContainer.java
  bundles/binding/org.openhab.binding.plcbus/src/main/java/org/openhab/binding/plcbus/internal/protocol/SerialPortGateway.java
Labels: awaiting-feedback

#5709 [Pushbullet] Update README.md with configuration parameters
  bundles/action/org.openhab.action.pushbullet/README.md
Labels: documentation

#5717 [Prowl] Correct configuration info in README
  bundles/action/org.openhab.action.prowl/README.md
Labels: documentation
