Repository openhab/openhab1-addons, pull requests merged in 2018-08, with the labels that each got.

#5630 [Zibase] Update and bug corrections(2)
  bundles/binding/org.openhab.binding.zibase/.classpath
  bundles/binding/org.openhab.binding.zibase/META-INF/MANIFEST.MF
  bundles/binding/org.openhab.binding.zibase/build.properties
  bundles/binding/org.openhab.binding.zibase/lib/jzapi-0.0.5.jar
  bundles/binding/org.openhab.binding.zibase/lib/jzapi-0.0.6.jar
  bundles/binding/org.openhab.binding.zibase/src/main/java/org/openhab/binding/zibase/internal/ZibaseBinding.java
  bundles/binding/org.openhab.binding.zibase/src/main/java/org/openhab/binding/zibase/internal/ZibaseBindingConfig.java
  bundles/binding/org.openhab.binding.zibase/src/main/java/org/openhab/binding/zibase/internal/ZibaseBindingConfigEmitter.java
  bundles/binding/org.openhab.binding.zibase/src/main/java/org/openhab/binding/zibase/internal/ZibaseBindingConfigReceiver.java
  bundles/binding/org.openhab.binding.zibase/src/main/java/org/openhab/binding/zibase/internal/ZibaseBindingConfigScenario.java
  bundles/binding/org.openhab.binding.zibase/src/main/java/org/openhab/binding/zibase/internal/ZibaseBindingConfigVariable.java
  bundles/binding/org.openhab.binding.zibase/src/main/java/org/openhab/binding/zibase/internal/ZibaseGenericBindingProvider.java
  bundles/binding/org.openhab.binding.zibase/src/main/java/org/openhab/binding/zibase/internal/ZibaseListener.java
Labels: enhancement

#5629 [velux] first version of the OH1 binding
  bundles/binding/org.openhab.binding.velux/.classpath
  bundles/binding/org.openhab.binding.velux/.gitignore
  bundles/binding/org.openhab.binding.velux/.project
  bundles/binding/org.openhab.binding.velux/.settings/org.eclipse.jdt.core.prefs
  bundles/binding/org.openhab.binding.velux/ESH-INF/binding/binding.xml
  bundles/binding/org.openhab.binding.velux/META-INF/MANIFEST.MF
  bundles/binding/org.openhab.binding.velux/OSGI-INF/binding.xml
  bundles/binding/org.openhab.binding.velux/OSGI-INF/genericbindingprovider.xml
  bundles/binding/org.openhab.binding.velux/README.md
  bundles/binding/org.openhab.binding.velux/build.properties
  bundles/binding/org.openhab.binding.velux/lib/gson-2.2.4.jar
  bundles/binding/org.openhab.binding.velux/pom.xml
  bundles/binding/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/VeluxBindingConstants.java
  bundles/binding/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/VeluxBindingProvider.java
  bundles/binding/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/bridge/VeluxBridge.java
  bundles/binding/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/bridge/VeluxBridgeDetectProducts.java
  bundles/binding/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/bridge/VeluxBridgeDeviceCheckLostNodes.java
  bundles/binding/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/bridge/VeluxBridgeDeviceStatus.java
  bundles/binding/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/bridge/VeluxBridgeExecute.java
  bundles/binding/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/bridge/VeluxBridgeFirmware.java
  bundles/binding/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/bridge/VeluxBridgeGetProducts.java
  bundles/binding/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/bridge/VeluxBridgeGetScenes.java
  bundles/binding/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/bridge/VeluxBridgeLANConfig.java
  bundles/binding/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/bridge/VeluxBridgeProvider.java
  bundles/binding/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/bridge/VeluxBridgeSceneMode.java
  bundles/binding/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/bridge/VeluxBridgeWLANConfig.java
  bundles/binding/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/bridge/comm/BCcheckLostNodes.java
  bundles/binding/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/bridge/comm/BCdetectProducts.java
  bundles/binding/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/bridge/comm/BCgetDeviceStatus.java
  bundles/binding/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/bridge/comm/BCgetFirmware.java
  bundles/binding/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/bridge/comm/BCgetLANConfig.java
  bundles/binding/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/bridge/comm/BCgetProducts.java
  bundles/binding/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/bridge/comm/BCgetScenes.java
  bundles/binding/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/bridge/comm/BCgetWLANConfig.java
  bundles/binding/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/bridge/comm/BCidentifyProduct.java
  bundles/binding/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/bridge/comm/BClogin.java
  bundles/binding/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/bridge/comm/BClogout.java
  bundles/binding/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/bridge/comm/BCrunScene.java
  bundles/binding/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/bridge/comm/BCsetSilentMode.java
  bundles/binding/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/bridge/comm/BridgeCommunicationProtocol.java
  bundles/binding/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/handler/VeluxBridgeHandlerOH1.java
  bundles/binding/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/VeluxActivator.java
  bundles/binding/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/VeluxBinding.java
  bundles/binding/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/VeluxBindingConfig.java
  bundles/binding/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/VeluxGenericBindingProvider.java
  bundles/binding/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/VeluxItemType.java
  bundles/binding/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/VeluxRSBindingConfig.java
  bundles/binding/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/config/VeluxBridgeConfiguration.java
  bundles/binding/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/things/VeluxExistingProducts.java
  bundles/binding/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/things/VeluxExistingScenes.java
  bundles/binding/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/things/VeluxProduct.java
  bundles/binding/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/things/VeluxProductReference.java
  bundles/binding/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/things/VeluxProductState.java
  bundles/binding/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/things/VeluxScene.java
  bundles/binding/pom.xml
  distribution/openhabhome/configurations/openhab_default.cfg
  features/openhab-addons-external/pom.xml
  features/openhab-addons-external/src/main/resources/conf/velux.cfg
Labels: new-binding-action-service

#5633 [Serial] Added setting to select charset for string encoding
  bundles/binding/org.openhab.binding.serial/README.md
  bundles/binding/org.openhab.binding.serial/src/main/java/org/openhab/binding/serial/internal/SerialBinding.java
  bundles/binding/org.openhab.binding.serial/src/main/java/org/openhab/binding/serial/internal/SerialDevice.java
Labels: enhancement

#5626 [NetworkUPSTools] Prevent ArrayIndexOutOfBoundsExceptions during configuration update
  bundles/binding/org.openhab.binding.networkupstools/src/main/java/org/openhab/binding/networkupstools/internal/NetworkUpsToolsBinding.java
Labels: bug
