Repository openhab/openhab1-addons, pull requests merged in 2018-04, with the labels that each got.

#5503 [Novelanheatpump] Add new simple state without time
  bundles/binding/org.openhab.binding.novelanheatpump/README.md
  bundles/binding/org.openhab.binding.novelanheatpump/src/main/java/org/openhab/binding/novelanheatpump/HeatpumpCommandType.java
  bundles/binding/org.openhab.binding.novelanheatpump/src/main/java/org/openhab/binding/novelanheatpump/internal/HeatPumpBinding.java
Labels: enhancement

#5483 [Pushover] Added Receipts and Callback API for handling of emergency-priority notifications
  bundles/action/org.openhab.action.pushover/META-INF/MANIFEST.MF
  bundles/action/org.openhab.action.pushover/README.md
  bundles/action/org.openhab.action.pushover/src/main/java/org/openhab/action/pushover/internal/Pushover.java
Labels: enhancement

#5532 Minor update to readme with Image Item example
  bundles/action/org.openhab.action.telegram/README.md
Labels: documentation

#5540 [FritzboxTr064] Update README.md
  bundles/binding/org.openhab.binding.fritzboxtr064/README.md
Labels: documentation

#5536 [FritzboxTr064] Fix the ArrayIndexOutOfBoundsException
  bundles/binding/org.openhab.binding.fritzboxtr064/META-INF/MANIFEST.MF
  bundles/binding/org.openhab.binding.fritzboxtr064/build.properties
  bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/CallEvent.java
  bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/CallMonitor.java
  bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/FritzboxTr064Binding.java
  bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/PhoneBookEntry.java
  bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/PhonebookManager.java
  bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/Tr064Comm.java
Labels: bug

#5544 [Telegram] Update README.md
  bundles/action/org.openhab.action.telegram/README.md
Labels: documentation

#5486 [Bticino] Several enhancements for Heating Control / Door Lock / Shutter / Dimmer
  bundles/binding/org.openhab.binding.bticino/README.md
  bundles/binding/org.openhab.binding.bticino/src/main/java/be/devlaminck/openwebnet/MonitorSessionThread.java
  bundles/binding/org.openhab.binding.bticino/src/main/java/be/devlaminck/openwebnet/OWNUtilities.java
  bundles/binding/org.openhab.binding.bticino/src/main/java/be/devlaminck/openwebnet/OpenWebNet.java
  bundles/binding/org.openhab.binding.bticino/src/main/java/com/myhome/fcrisciani/connector/MyHomeJavaConnector.java
  bundles/binding/org.openhab.binding.bticino/src/main/java/org/openhab/binding/bticino/internal/BticinoBinding.java
  bundles/binding/org.openhab.binding.bticino/src/main/java/org/openhab/binding/bticino/internal/BticinoDevice.java
  bundles/binding/org.openhab.binding.bticino/src/main/java/org/openhab/binding/bticino/internal/BticinoGenericBindingProvider.java
  distribution/openhabhome/configurations/openhab_default.cfg
  features/openhab-addons-external/src/main/resources/conf/bticino.cfg
Labels: enhancement

#5543 [Serial] Fix configuration parsing error in the serial binding
  bundles/binding/org.openhab.binding.serial/META-INF/MANIFEST.MF
  bundles/binding/org.openhab.binding.serial/README.md
  bundles/binding/org.openhab.binding.serial/src/main/java/org/openhab/binding/serial/internal/SerialBinding.java
  bundles/binding/org.openhab.binding.serial/src/main/java/org/openhab/binding/serial/internal/SerialDevice.java
Labels: bug

#5527 [Pushover] added support for attachment/image push
  bundles/action/org.openhab.action.pushover/META-INF/MANIFEST.MF
  bundles/action/org.openhab.action.pushover/README.md
  bundles/action/org.openhab.action.pushover/src/main/java/org/openhab/action/pushover/internal/Pushover.java
Labels: enhancement

#5550 proposed solution for "[Tinkerforge] Readme is wrong #5545"
  bundles/binding/org.openhab.binding.tinkerforge/README.md
Labels: documentation

#5547 [FritzboxTr064] Fixed some examples in FritzBox TR064-Readme
  bundles/binding/org.openhab.binding.fritzboxtr064/README.md
Labels: documentation

#5516 [Pushbullet] Added ability to push notes to a channel
  bundles/action/org.openhab.action.pushbullet/META-INF/MANIFEST.MF
  bundles/action/org.openhab.action.pushbullet/README.md
  bundles/action/org.openhab.action.pushbullet/src/main/java/org/openhab/action/pushbullet/internal/PushbulletAPIConnector.java
  bundles/action/org.openhab.action.pushbullet/src/main/java/org/openhab/action/pushbullet/internal/model/Push.java
Labels: enhancement
