Repository openhab/openhab1-addons, pull requests merged in 2018-07, with the labels that each got.

#5607 [vdr1] change logLevel for could not connect to DEBUG
  bundles/binding/org.openhab.binding.vdr/src/main/java/org/openhab/binding/vdr/internal/VDRConnection.java
Labels: enhancement

#5598 [MPD][Documentation] Fix an error and change a bit of wording
  bundles/binding/org.openhab.binding.mpd/README.md
Labels: documentation, enhancement

#5624 [Zibase] Cleaning the zibase message buffer: fix of #5623
  bundles/binding/org.openhab.binding.zibase/src/main/java/org/openhab/binding/zibase/internal/ZibaseListener.java
Labels: bug
