Repository openhab/openhab1-addons, pull requests merged in 2018-06, with the labels that each got.

#5593 [TCP][Documentation] Update Readme.md
  bundles/binding/org.openhab.binding.tcp/README.md
Labels: documentation, enhancement

#5595 [XMPP][Documentation] Update README with new example
  bundles/action/org.openhab.action.xmpp/README.md
Labels: documentation, enhancement

#5591 [MapDB] Fix new items not immediately persisted, upgrade to mapdb-1.0.9
  bundles/persistence/org.openhab.persistence.mapdb/.classpath
  bundles/persistence/org.openhab.persistence.mapdb/META-INF/MANIFEST.MF
  bundles/persistence/org.openhab.persistence.mapdb/build.properties
  bundles/persistence/org.openhab.persistence.mapdb/lib/mapdb-1.0.7.jar
  bundles/persistence/org.openhab.persistence.mapdb/lib/mapdb-1.0.9.jar
  bundles/persistence/org.openhab.persistence.mapdb/src/main/java/org/openhab/persistence/mapdb/internal/MapDBPersistenceService.java
Labels: bug

#5599 [Cardio2e][Documentation] Added README.md
  bundles/binding/org.openhab.binding.cardio2e/README.md
Labels: documentation

#5582 [Weather][ForecastIo] Get UV-Index and Wind Gust from forecast.io
  bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/model/Atmosphere.java
  bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/model/Wind.java
Labels: enhancement

#5577 [ComfoAir][Documentation] - Add undocumented features
  bundles/binding/org.openhab.binding.comfoair/README.md
Labels: documentation, enhancement
