Repository openhab/openhab1-addons, pull requests merged in 2019-12, with the labels that each got.

#5868 Fixed restriction on special characters in URLs
  bundles/binding/org.openhab.binding.caldav-personal/README.md
Labels: documentation

#5877 [fatekplc] Added serial port support
  bundles/binding/org.openhab.binding.fatekplc/.classpath
  bundles/binding/org.openhab.binding.fatekplc/META-INF/MANIFEST.MF
  bundles/binding/org.openhab.binding.fatekplc/README.md
  bundles/binding/org.openhab.binding.fatekplc/build.properties
  bundles/binding/org.openhab.binding.fatekplc/lib/jfatek-2.0.0-sources.jar
  bundles/binding/org.openhab.binding.fatekplc/lib/jfatek-2.0.0.jar
  bundles/binding/org.openhab.binding.fatekplc/pom.xml
  bundles/binding/org.openhab.binding.fatekplc/src/main/java/org/openhab/binding/fatekplc/internal/FatekPLCSlave.java
  bundles/binding/org.openhab.binding.fatekplc/src/main/java/org/openhab/binding/fatekplc/serial/SerialFatekConnectionFactory.java
  bundles/binding/org.openhab.binding.fatekplc/src/main/resources/jfatek/SERIALFatekConnectionFactory
  features/openhab-addons-external/src/main/resources/conf/fatekplc.cfg
  features/openhab-addons/src/main/feature/feature.xml
Labels: enhancement

#5685 [swegon] Added throttle support
  bundles/binding/org.openhab.binding.swegonventilation/README.md
  bundles/binding/org.openhab.binding.swegonventilation/src/main/java/org/openhab/binding/swegonventilation/internal/SwegonVentilationBinding.java
  bundles/binding/org.openhab.binding.swegonventilation/src/main/java/org/openhab/binding/swegonventilation/protocol/SwegonVentilationDataParser.java
Labels: enhancement

#5684 [oem] throttle support
  bundles/binding/org.openhab.binding.openenergymonitor/README.md
  bundles/binding/org.openhab.binding.openenergymonitor/src/main/java/org/openhab/binding/openenergymonitor/internal/OpenEnergyMonitorBinding.java
  bundles/binding/org.openhab.binding.openenergymonitor/src/main/java/org/openhab/binding/openenergymonitor/protocol/OpenEnergyMonitorDataParser.java
Labels: enhancement

#5828 [anel] Added Masking of passwords in log entries
  bundles/binding/org.openhab.binding.anel/src/main/java/org/openhab/binding/anel/internal/AnelConnectorThread.java
Labels: enhancement

#5794 [Davis] Formatting changes for README
  bundles/binding/org.openhab.binding.davis/README.md
Labels: awaiting-feedback, documentation

#5793 [Daikin] Formatting changes for README
  bundles/binding/org.openhab.binding.daikin/README.md
Labels: documentation

#5796 [Diyonxbee] Formatting changes for README
  bundles/binding/org.openhab.binding.diyonxbee/README.md
Labels: documentation

#5789 [CalDAV-Command] Readability enhancements for README
  bundles/binding/org.openhab.binding.caldav-command/README.md
Labels: awaiting-feedback, documentation

#5792 [Cups] Update README with better sendCommand alternative
  bundles/binding/org.openhab.binding.cups/README.md
Labels: awaiting-feedback, documentation

#5780 [MCP23017] Fix minor typos in README
  bundles/binding/org.openhab.binding.mcp23017/README.md
Labels: awaiting-feedback, documentation

#5790 [CalDAV-Personal] Minor cleanup for README
  bundles/binding/org.openhab.binding.caldav-personal/README.md
Labels: documentation

#5779 [SNMP] Update README.md for the version property
  bundles/binding/org.openhab.binding.snmp/README.md
Labels: documentation

#5718 [http] Fixed NPE while executing background thread
  bundles/binding/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/HttpBinding.java
Labels: bug

#5614 Update README.md
  bundles/binding/org.openhab.binding.caldav-personal/README.md
Labels: documentation, enhancement

#5921 [Bticino] Update OpenWebNet link in README, current link is dead
  bundles/binding/org.openhab.binding.bticino/README.md
Labels: documentation
