Repository openhab/openhab1-addons, pull requests merged in 2019-01, with the labels that each got.

#5702 [Weather] Remove the yahoo weather provider
  bundles/binding/org.openhab.binding.weather/README.md
  bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/common/LocationConfig.java
  bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/common/WeatherConfig.java
  bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/model/Atmosphere.java
  bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/model/Condition.java
  bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/model/ProviderName.java
  bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/model/Temperature.java
  bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/model/Weather.java
  bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/model/Wind.java
  bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/provider/WeatherProviderFactory.java
  bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/provider/YahooProvider.java
  bundles/binding/org.openhab.binding.weather/src/main/resources/weather/common-id-mappings.xml
Labels: enhancement

#5757 [weather] Fix typo in error message
  bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/provider/AbstractWeatherProvider.java
Labels: enhancement

#5750 [Weather] Add two new Provider APIXU and Weatherbit.
  bundles/binding/org.openhab.binding.weather/README.md
  bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/common/WeatherConfig.java
  bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/converter/property/UnixDateConverter.java
  bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/model/Atmosphere.java
  bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/model/Clouds.java
  bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/model/Condition.java
  bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/model/Precipitation.java
  bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/model/ProviderName.java
  bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/model/Station.java
  bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/model/Temperature.java
  bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/model/Weather.java
  bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/model/Wind.java
  bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/provider/AbstractWeatherProvider.java
  bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/provider/ApiXuProvider.java
  bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/provider/WeatherProviderFactory.java
  bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/provider/WeatherbitProvider.java
  bundles/binding/org.openhab.binding.weather/src/main/resources/weather/common-id-mappings.xml
Labels: enhancement

#5755 [Fritzbox] Update README.md with notes about removed Telnet support
  bundles/binding/org.openhab.binding.fritzbox/README.md
Labels: awaiting-feedback

#5768 [Persistence] Corrected the InfluxDB web page link
  bundles/persistence/org.openhab.persistence.influxdb/README.md
Labels: documentation

#5765 [Telegram] Support for formatted messages
  bundles/action/org.openhab.action.telegram/README.md
  bundles/action/org.openhab.action.telegram/src/main/java/org/openhab/action/telegram/internal/Telegram.java
  bundles/action/org.openhab.action.telegram/src/main/java/org/openhab/action/telegram/internal/TelegramActionService.java
  bundles/action/org.openhab.action.telegram/src/main/java/org/openhab/action/telegram/internal/TelegramBot.java
  distribution/openhabhome/configurations/openhab_default.cfg
  features/openhab-addons-external/src/main/resources/conf/telegram.cfg
Labels: enhancement

#5775 [InsteonPLM] Add OnLevel feature to Insteon PLM 2477D dimmer
  bundles/binding/org.openhab.binding.insteonplm/src/main/resources/device_features.xml
  bundles/binding/org.openhab.binding.insteonplm/src/main/resources/device_types.xml
Labels: enhancement

#5769 [pilight] Add pilight feature
  features/openhab-addons-external/pom.xml
  features/openhab-addons-external/src/main/resources/conf/pilight.cfg
  features/openhab-addons/src/main/feature/feature.xml
Labels: enhancement
